language: c

sudo: false

cache:
  directories:
    - $HOME/.cache/latex

addons:
  apt:
  packages:
      - wget
      - curl
      - sed
      - grep
      - texlive
      - texlive-generic-extra
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-math-extra
      - texlive-metapost
      - texlive-omega
      - texlive-plain-extra
      - texlive-xetex

env:
 global:
   - secure: "ehec8FC6y923UXtB2fMULF/xkQJkwWwzD6xFxyz0lc80IqR8Rmxh16nLKGxI9jD11qjbYSzp1yPVadXyBoSheop5aZPxeXixL49y26ikIRkyuQQdHyjsM34etoPmCKw2vVXvD+JAwjTa6qYpihSOdDXltog8ZNHF6Wp28ZaWW8g="

matrix:
 include:
# only one of these should have UPDATE_ERRATA set to "yes", otherwise we risk race conditions on pushing
   - env: LATEXMK="yes" UPDATE_ERRATA=""     UPDATE_NIGHTLIES=""     TARGETS=""
   - env: LATEXMK=""    UPDATE_ERRATA="yes"  UPDATE_NIGHTLIES="yes"  TARGETS=""
   - env: LATEXMK=""    UPDATE_ERRATA=""     UPDATE_NIGHTLIES=""     TARGETS="dvi"


install:
 - test -z "$LATEXMK" || which latexmk

script: make $TARGETS

# add -f to force a push even if we're not on HoTT/HoTT.
# generally only useful for debugging
after_script:
 - etc/ci/update_errata.sh
 - etc/ci/update_nightlies.sh
